(function(){
var API='/api/deepseek';
var COST_KEY='personalOS.aiCost.v1';
function money(n){return '€'+(Number(n)||0).toFixed(4)}
function todayKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function monthKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function loadCost(){try{return JSON.parse(localStorage.getItem(COST_KEY)||'{}')||{}}catch(e){return{}}}
function saveCost(v){try{localStorage.setItem(COST_KEY,JSON.stringify(v))}catch(e){}}
function addCost(v){var c=loadCost(),d=todayKey(),m=monthKey(),x=Number(v)||0;c.daily=c.daily||{};c.monthly=c.monthly||{};c.daily[d]=(Number(c.daily[d])||0)+x;c.monthly[m]=(Number(c.monthly[m])||0)+x;saveCost(c);renderCost()}
function renderCost(){var el=document.getElementById('aiCostBadge');if(!el)return;var c=loadCost(),d=todayKey(),m=monthKey();el.innerHTML='<div><span>AI TODAY</span><b>'+money(c.daily&&c.daily[d])+'</b></div><div><span>AI MONTH</span><b>'+money(c.monthly&&c.monthly[m])+'</b></div>'}
function injectCost(){var nav=document.querySelector('.topbar .nav');if(!nav)return;var el=document.getElementById('aiCostBadge');if(!el){el=document.createElement('div');el.id='aiCostBadge';el.className='aiCostBadge'}var today=Array.prototype.find.call(nav.children,function(n){return /^TODAY$/i.test((n.textContent||'').trim())});if(today)nav.insertBefore(el,today);else nav.appendChild(el);renderCost()}
function stableTodoCss(){var old=document.getElementById('ai-stable-todo-css');if(old)old.remove();var s=document.createElement('style');s.id='ai-stable-todo-css';s.textContent='#todoView .todoMain .table{table-layout:fixed!important;width:100%!important}#todoView .todoMain .taskText{width:100%!important;max-width:none!important;display:flex!important;align-items:center!important;gap:10px!important;overflow:visible!important}#todoView .taskTextInput,#todoView .taskPill,#todoView input.taskPill,#todoView textarea.taskPill{width:calc(100% - 44px)!important;max-width:calc(100% - 44px)!important;min-width:calc(100% - 44px)!important;box-sizing:border-box!important;flex:0 0 calc(100% - 44px)!important;transition:none!important;resize:none!important;overflow:hidden!important;transform:none!important}#todoView .dragCell{flex:0 0 24px!important;width:24px!important;min-width:24px!important;max-width:24px!important}#todoView .todoRow,#todoView .todoRow td,#todoView .taskText,#todoView .taskPill,#todoView .taskTextInput{transition:none!important;animation:none!important}';document.head.appendChild(s)}
function addStyle(){var s=document.createElement('style');s.textContent='.aiChatButton{position:fixed;left:10px;bottom:18px;width:62px;height:62px;border-radius:19px;z-index:100;border:2px solid #8f5cff;background:linear-gradient(180deg,#21113f,#090615);color:#fff;font-size:27px;box-shadow:0 0 0 1px rgba(255,255,255,.06),0 0 14px rgba(143,92,255,.26),0 12px 24px rgba(0,0,0,.45)}.aiChatButton:hover{border-color:#b990ff;background:linear-gradient(180deg,#321960,#100827);box-shadow:0 0 0 1px rgba(255,255,255,.08),0 0 18px rgba(169,120,255,.32),0 12px 26px rgba(0,0,0,.48)}.aiChatPanel{position:fixed;left:20px;bottom:96px;width:min(420px,calc(100vw - 36px));height:560px;display:none;flex-direction:column;z-index:100;border:1px solid #4b3170;border-radius:18px;background:#050509;overflow:hidden}.aiChatPanel.open{display:flex}.aiChatHeader{padding:14px;border-bottom:1px solid #2b2147;font-weight:1000}.aiChatMessages{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:10px}.aiMsg{border:1px solid #352456;background:#090812;border-radius:12px;padding:10px;line-height:1.35;white-space:pre-wrap}.aiMsg.user{border-color:#7f52ff}.aiChatInput{display:flex;gap:8px;padding:12px;border-top:1px solid #2b2147}.aiChatInput input{flex:1}.aiChatInput button{height:40px}.aiCostBadge{height:48px;min-width:190px;border:1px solid #342457;border-radius:12px;background:linear-gradient(180deg,#100b1d,#070710);display:flex;align-items:center;justify-content:center;gap:16px;padding:0 14px;margin:0 10px;color:#fff;font-weight:1000}.aiCostBadge div{display:flex;flex-direction:column;line-height:1.05}.aiCostBadge span{font-size:10px;color:#a99dc5;letter-spacing:.12em}.aiCostBadge b{font-size:14px;color:#fff;letter-spacing:.04em}#scheduleView .event{position:absolute!important}#scheduleView .event .time,#scheduleView .event .title{position:relative;z-index:2}#scheduleView .event.time-current::after,#scheduleView .event.time-past::after{display:none!important}.aiLiveProgressFill{position:absolute;left:0;right:0;top:0;height:0;border-radius:inherit;background:linear-gradient(180deg,rgba(255,255,255,.22),rgba(255,255,255,.07));pointer-events:none;z-index:1;mix-blend-mode:screen}.aiLiveNowLine{position:absolute;left:0;right:0;height:2px;background:#fff;box-shadow:0 0 8px rgba(255,255,255,.75),0 0 18px rgba(155,108,255,.55);z-index:70;pointer-events:none}.aiLiveNowLine::before{content:"";position:absolute;left:-5px;top:-4px;width:10px;height:10px;border-radius:50%;background:#fff;box-shadow:0 0 10px rgba(255,255,255,.8)}';document.head.appendChild(s);stableTodoCss()}
function addHtml(){document.body.insertAdjacentHTML('beforeend','<button class="aiChatButton" id="aiChatButton" title="DeepSeek Assistant">✦</button><div class="aiChatPanel" id="aiChatPanel"><div class="aiChatHeader">DeepSeek Assistant</div><div class="aiChatMessages" id="aiChatMessages"></div><div class="aiChatInput"><input id="aiChatInput" placeholder="Ask me to plan your tasks..."><button id="aiChatSend">SEND</button></div></div>')}
function taskMins(text){var p=String(text||'').toLowerCase().match(/\(([^)]*)\)/),r=p?p[1]:'',m=0,h=r.match(/(\d+(?:\.\d+)?)\s*(h|hour|hours)/),mi=r.match(/(\d+)\s*(m|min|mins|minute|minutes)/);if(h)m+=Math.round(parseFloat(h[1])*60);if(mi)m+=parseInt(mi[1],10);if(!m&&/^\d+$/.test(r))m=parseInt(r,10);return m||null}
function eventTimes(el){var t=(el.querySelector('.time')||{}).textContent||'';var m=t.match(/(\d{1,2}):(\d{2})\s*-\s*(\d{1,2}):(\d{2})/);if(!m)return null;return{start:Number(m[1])*60+Number(m[2]),end:Number(m[3])*60+Number(m[4])}}
function nowMinutes(){var d=new Date();return d.getHours()*60+d.getMinutes()+d.getSeconds()/60}
function syncLiveProgress(){try{var now=nowMinutes();document.querySelectorAll('#scheduleView .event').forEach(function(el){var times=eventTimes(el);if(!times)return;var isToday=!!el.closest('.todayCol');el.classList.remove('time-current','time-past','time-future','time-neutral');el.querySelectorAll('.aiLiveProgressFill').forEach(function(x){x.remove()});if(!isToday){el.classList.add('time-neutral');return}if(now<times.start){el.classList.add('time-future');return}if(now>=times.end){el.classList.add('time-past');return}el.classList.add('time-current');var fill=document.createElement('div');fill.className='aiLiveProgressFill';fill.style.height=Math.max(0,Math.min(100,((now-times.start)/(times.end-times.start))*100))+'%';el.insertBefore(fill,el.firstChild)});var grid=document.querySelector('#scheduleView .todayCol .grid');var line=document.getElementById('aiLiveNowLine');if(!grid){if(line)line.remove();return}if(!line){line=document.createElement('div');line.id='aiLiveNowLine';line.className='aiLiveNowLine'}var top=(now-START)*PX;if(now<START||now>END){if(line.parentNode)line.remove();return}line.style.top=top+'px';if(line.parentNode!==grid)grid.appendChild(line)}catch(e){}}
function weekData(){var w=isoWeek(currentMonday),out=[];for(var i=0;i<7;i++){var d=addDays(currentMonday,i),date=ymd(d);out.push({date:date,dayName:DAYS[i],blocks:blocksFor(d,i,w).map(function(b){return{id:b.id,date:b.date,start:b.start,end:b.end,title:b.title,type:b.type,source:b.source,isEditable:b.type!=='school',isDefaultFreeBlock:b.source==='system'&&['focus','homework','break'].indexOf(b.type)>-1}})})}return out}
function readApp(){return{currentMonday:ymd(currentMonday),tasks:tasks.map(function(t){return{id:t.id,done:!!t.done,text:t.text,day:t.day,area:t.area,durationMinutes:taskMins(t.text)}}),week:weekData()}}
function fits(a){var d=weekData().find(function(x){return x.date===a.date});return !!(d&&d.blocks.some(function(b){return b.isDefaultFreeBlock&&min(b.start)<=min(a.start)&&min(a.end)<=min(b.end)}))}
function customOverlap(a){return state.custom.some(function(c){return c.date===a.date&&min(a.start)<min(c.end)&&min(c.start)<min(a.end)})}
function applyActions(actions){if(!Array.isArray(actions)||!actions.length)return;pushHistory();var n=0;actions.forEach(function(a){if(a.type!=='assign_task_to_block')return;var t=tasks.find(function(x){return x.id===a.taskId});if(!t||t.done||!a.date||!a.start||!a.end||min(a.start)>=min(a.end)||!fits(a)||customOverlap(a))return;state.custom.push({id:uid(),date:a.date,start:a.start,end:a.end,title:a.title||t.text.replace(/\([^)]*\)/g,'').trim(),type:a.blockType||inferType(t.text),source:'custom',aiCreated:true,taskId:t.id});t.assigned=true;n++});if(n){saveState();saveTasks();render();setTimeout(syncLiveProgress,0);toast('AI updated your schedule')}else{history.pop();saveJson(HK,history);updateUndoUi();toast('No changes applied')}}
function addMsg(t,who){var box=document.getElementById('aiChatMessages'),d=document.createElement('div');d.className='aiMsg '+(who||'assistant');d.textContent=t;box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
async function send(){var input=document.getElementById('aiChatInput'),text=input.value.trim();if(!text)return;input.value='';addMsg(text,'user');var p=addMsg('Working...','assistant');try{var r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,appState:readApp()})});var data=await r.json();p.remove();if(!r.ok){addMsg(data.error||'Request failed.','assistant');return}if(typeof data.costEUR==='number')addCost(data.costEUR);if(data.costPricingConfigured===false)addMsg('Cost tracking is active, but EUR pricing env vars are not configured yet.','assistant');addMsg(data.message||'Done.','assistant');applyActions(data.actions||[])}catch(e){p.remove();addMsg('Could not reach /api/deepseek.','assistant')}}
function boot(){addStyle();addHtml();injectCost();syncLiveProgress();setInterval(function(){injectCost();stableTodoCss();syncLiveProgress()},1200);setInterval(syncLiveProgress,15000);document.getElementById('aiChatButton').onclick=function(){document.getElementById('aiChatPanel').classList.toggle('open')};document.getElementById('aiChatSend').onclick=send;document.getElementById('aiChatInput').addEventListener('keydown',function(e){if(e.key==='Enter')send()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
