(function(){
var API='/api/deepseek';
var COST_KEY='personalOS.aiCost.v1';
function money(n){return '€'+(Number(n)||0).toFixed(4)}
function todayKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function monthKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function loadCost(){try{return JSON.parse(localStorage.getItem(COST_KEY)||'{}')||{}}catch(e){return{}}}
function saveCost(v){try{localStorage.setItem(COST_KEY,JSON.stringify(v))}catch(e){}}
function addCost(v){var c=loadCost(),d=todayKey(),m=monthKey(),x=Number(v)||0;c.daily=c.daily||{};c.monthly=c.monthly||{};c.daily[d]=(Number(c.daily[d])||0)+x;c.monthly[m]=(Number(c.monthly[m])||0)+x;saveCost(c);renderCost()}
function renderCost(){var el=document.getElementById('aiCostBadge');if(!el)return;var c=loadCost(),d=todayKey(),m=monthKey();el.innerHTML='<div><span>AI TODAY</span><b>'+money(c.daily&&c.daily[d])+'</b></div><div><span>AI MONTH</span><b>'+money(c.monthly&&c.monthly[m])+'</b></div>'}
function injectCost(){if(document.getElementById('aiCostBadge'))return;var nav=document.querySelector('.topbar .nav');if(!nav)return;var el=document.createElement('div');el.id='aiCostBadge';el.className='aiCostBadge';nav.insertBefore(el,nav.firstChild);renderCost()}
function stableTodoCss(){var s=document.createElement('style');s.id='ai-stable-todo-css';s.textContent='#todoView .todoMain .table{table-layout:fixed!important;width:100%!important}#todoView .todoMain .taskText{width:100%!important;max-width:none!important;display:flex!important;align-items:center!important;gap:10px!important;overflow:visible!important}#todoView .taskTextInput,#todoView .taskPill,#todoView input.taskPill,#todoView textarea.taskPill{width:calc(100% - 44px)!important;max-width:calc(100% - 44px)!important;min-width:calc(100% - 44px)!important;box-sizing:border-box!important;flex:0 0 calc(100% - 44px)!important;transition:none!important;resize:none!important;overflow:hidden!important;transform:none!important}#todoView .dragCell{flex:0 0 24px!important;width:24px!important;min-width:24px!important;max-width:24px!important}#todoView .todoRow,#todoView .todoRow td,#todoView .taskText,#todoView .taskPill,#todoView .taskTextInput{transition:none!important;animation:none!important}';document.head.appendChild(s)}
function addStyle(){var s=document.createElement('style');s.textContent='.aiChatButton{position:fixed;left:32px;bottom:18px;width:64px;height:64px;border-radius:20px;z-index:100;border:2px solid #a978ff;background:linear-gradient(180deg,#2c1559,#0d0820);color:#fff;font-size:28px;box-shadow:0 0 0 1px rgba(255,255,255,.12),0 0 32px rgba(169,120,255,.50),0 18px 40px rgba(0,0,0,.55)}.aiChatButton:hover{border-color:#d4b8ff;background:linear-gradient(180deg,#432080,#160c34)}.aiChatPanel{position:fixed;left:20px;bottom:96px;width:min(420px,calc(100vw - 36px));height:560px;display:none;flex-direction:column;z-index:100;border:1px solid #4b3170;border-radius:18px;background:#050509;overflow:hidden}.aiChatPanel.open{display:flex}.aiChatHeader{padding:14px;border-bottom:1px solid #2b2147;font-weight:1000}.aiChatMessages{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:10px}.aiMsg{border:1px solid #352456;background:#090812;border-radius:12px;padding:10px;line-height:1.35;white-space:pre-wrap}.aiMsg.user{border-color:#7f52ff}.aiChatInput{display:flex;gap:8px;padding:12px;border-top:1px solid #2b2147}.aiChatInput input{flex:1}.aiChatInput button{height:40px}.aiCostBadge{height:48px;min-width:190px;border:1px solid #342457;border-radius:12px;background:linear-gradient(180deg,#100b1d,#070710);display:flex;align-items:center;justify-content:center;gap:16px;padding:0 14px;color:#fff;font-weight:1000}.aiCostBadge div{display:flex;flex-direction:column;line-height:1.05}.aiCostBadge span{font-size:10px;color:#a99dc5;letter-spacing:.12em}.aiCostBadge b{font-size:14px;color:#49ff9f;letter-spacing:.04em}';document.head.appendChild(s);stableTodoCss()}
function addHtml(){document.body.insertAdjacentHTML('beforeend','<button class="aiChatButton" id="aiChatButton" title="DeepSeek Assistant">✦</button><div class="aiChatPanel" id="aiChatPanel"><div class="aiChatHeader">DeepSeek Assistant</div><div class="aiChatMessages" id="aiChatMessages"></div><div class="aiChatInput"><input id="aiChatInput" placeholder="Ask me to plan your tasks..."><button id="aiChatSend">SEND</button></div></div>')}
function taskMins(text){var p=String(text||'').toLowerCase().match(/\(([^)]*)\)/),r=p?p[1]:'',m=0,h=r.match(/(\d+(?:\.\d+)?)\s*(h|hour|hours)/),mi=r.match(/(\d+)\s*(m|min|mins|minute|minutes)/);if(h)m+=Math.round(parseFloat(h[1])*60);if(mi)m+=parseInt(mi[1],10);if(!m&&/^\d+$/.test(r))m=parseInt(r,10);return m||null}
function weekData(){var w=isoWeek(currentMonday),out=[];for(var i=0;i<7;i++){var d=addDays(currentMonday,i),date=ymd(d);out.push({date:date,dayName:DAYS[i],blocks:blocksFor(d,i,w).map(function(b){return{id:b.id,date:b.date,start:b.start,end:b.end,title:b.title,type:b.type,source:b.source,isEditable:b.type!=='school',isDefaultFreeBlock:b.source==='system'&&['focus','homework','break'].indexOf(b.type)>-1}})})}return out}
function readApp(){return{currentMonday:ymd(currentMonday),tasks:tasks.map(function(t){return{id:t.id,done:!!t.done,text:t.text,day:t.day,area:t.area,durationMinutes:taskMins(t.text)}}),week:weekData()}}
function fits(a){var d=weekData().find(function(x){return x.date===a.date});return !!(d&&d.blocks.some(function(b){return b.isDefaultFreeBlock&&min(b.start)<=min(a.start)&&min(a.end)<=min(b.end)}))}
function customOverlap(a){return state.custom.some(function(c){return c.date===a.date&&min(a.start)<min(c.end)&&min(c.start)<min(a.end)})}
function applyActions(actions){if(!Array.isArray(actions)||!actions.length)return;pushHistory();var n=0;actions.forEach(function(a){if(a.type!=='assign_task_to_block')return;var t=tasks.find(function(x){return x.id===a.taskId});if(!t||t.done||!a.date||!a.start||!a.end||min(a.start)>=min(a.end)||!fits(a)||customOverlap(a))return;state.custom.push({id:uid(),date:a.date,start:a.start,end:a.end,title:a.title||t.text.replace(/\([^)]*\)/g,'').trim(),type:a.blockType||inferType(t.text),source:'custom',aiCreated:true,taskId:t.id});t.assigned=true;n++});if(n){saveState();saveTasks();render();toast('AI updated your schedule')}else{history.pop();saveJson(HK,history);updateUndoUi();toast('No changes applied')}}
function addMsg(t,who){var box=document.getElementById('aiChatMessages'),d=document.createElement('div');d.className='aiMsg '+(who||'assistant');d.textContent=t;box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
async function send(){var input=document.getElementById('aiChatInput'),text=input.value.trim();if(!text)return;input.value='';addMsg(text,'user');var p=addMsg('Working...','assistant');try{var r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,appState:readApp()})});var data=await r.json();p.remove();if(!r.ok){addMsg(data.error||'Request failed.','assistant');return}if(typeof data.costEUR==='number')addCost(data.costEUR);if(data.costPricingConfigured===false)addMsg('Cost tracking is active, but EUR pricing env vars are not configured yet.','assistant');addMsg(data.message||'Done.','assistant');applyActions(data.actions||[])}catch(e){p.remove();addMsg('Could not reach /api/deepseek.','assistant')}}
function boot(){addStyle();addHtml();injectCost();setInterval(function(){injectCost();stableTodoCss()},1200);document.getElementById('aiChatButton').onclick=function(){document.getElementById('aiChatPanel').classList.toggle('open')};document.getElementById('aiChatSend').onclick=send;document.getElementById('aiChatInput').addEventListener('keydown',function(e){if(e.key==='Enter')send()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
