// Personal OS stable loader + schedule polish + model-driven assistant
(function(){
const BASE='https://raw.githubusercontent.com/mathiashansen275-arch/personal-os/50bd59a53b151fd3deac3b2bbd34521945c4ce16/lectio-data.js';
const STATE='personalOS.schedule.v5';
const PX=1.22;
const GAP=4;
let raf=0;
const pad=n=>String(n).padStart(2,'0');
const hm=m=>pad(Math.floor(m/60))+':'+pad(Math.round(m%60));
const mins=s=>{s=String(s||'00:00');return Number(s.slice(0,2))*60+Number(s.slice(3,5))};
const ymd=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const clean=s=>String(s||'').replace(/^\s*2i\s+/i,'').replace(/^\s*available block\s*$/i,'').replace(/\s+/g,' ').trim();
const ptime=s=>{const m=String(s||'').match(/(\d{1,2}):(\d{2})\s*-\s*(\d{1,2}):(\d{2})/);return m?{start:+m[1]*60+ +m[2],end:+m[3]*60+ +m[4],raw:m[0]}:null};
const esc=s=>String(s||'').replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]));
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'')||d}catch(e){return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const getState=()=>{try{return state}catch(e){return load(STATE,{custom:[]})}};
const setState=s=>{try{state=s}catch(e){}save(STATE,s)};
function getTasks(){try{if(Array.isArray(tasks))return tasks}catch(e){}try{if(Array.isArray(window.tasks))return window.tasks}catch(e){}return[]}
function taskContext(){try{return getTasks().map((t,i)=>({id:t.id||'task-'+i,priority:i+1,text:t.text||t.title||'',done:!!t.done}))}catch(e){return[]}}
function weekContext(){let out=[];try{let w=isoWeek(currentMonday);for(let i=0;i<7;i++){let d=addDays(currentMonday,i);out.push({date:ymd(d),dayIndex:i,blocks:blocksFor(d,i,w)})}}catch(e){}return out}
function css(){let s=document.getElementById('pos-restored-polish');if(!s){s=document.createElement('style');s.id='pos-restored-polish';document.head.appendChild(s)}s.textContent=`
#addBlock,#revertWeek{display:none!important}
body:not(.aiScheduleActive) #prev,body:not(.aiScheduleActive) #next,body:not(.aiScheduleActive) #today{display:none!important}
#scheduleView .event,#scheduleView .event:hover{transition:none!important;animation:none!important;transform:none!important;filter:none!important;box-shadow:none!important}
#scheduleView .event.break,#scheduleView .event.aiBreakHidden,#scheduleView .event.aiFreeHidden,#scheduleView .event.focus:not(.business):not(.personal),#scheduleView .event.deep:not(.business):not(.personal){display:none!important}
#scheduleView .event.aiLockedGenerated{cursor:default!important}
#scheduleView .event .time{font-weight:760!important;text-align:left!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;max-width:100%!important}
#scheduleView .event .title{font-weight:650!important;text-align:left!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;max-width:100%!important}
#scheduleView .event.aiOneLineSmall{display:flex!important;flex-direction:column!important;justify-content:center!important;align-items:stretch!important;text-align:left!important;padding-top:1px!important;padding-bottom:1px!important}
#scheduleView .event.aiOneLineSmall .time{display:block!important;width:100%!important;max-width:100%!important;white-space:nowrap!important;overflow:visible!important;text-overflow:clip!important;text-align:left!important;font-size:11.5px!important;line-height:1!important;font-weight:760!important;padding-right:0!important;letter-spacing:-.015em!important}
#scheduleView .event.aiOneLineSmall .title,#scheduleView .event.homework .title,#scheduleView .event.wind .title{display:none!important}
#scheduleView .event.homework .time,#scheduleView .event.wind .time{white-space:nowrap!important;overflow:visible!important;text-overflow:clip!important;font-size:11.5px!important;letter-spacing:-.015em!important;line-height:1!important}
#scheduleView .event.business{background:rgba(48,64,24,.72)!important;border-color:#9caf55!important;color:#dbe8a6!important}
#scheduleView .event.business .time,#scheduleView .event.business .title{color:#dbe8a6!important}
#scheduleView .event.personal{background:rgba(76,0,45,.58)!important;border-color:#ff45d6!important;color:#ff69e2!important}
#scheduleView .event.personal .time,#scheduleView .event.personal .title{color:#ff69e2!important}
#scheduleView .event.personalTime{background:rgba(83,55,23,.72)!important;border-color:#ffb454!important;color:#ffd9a0!important}
#scheduleView .event.personalTime .time,#scheduleView .event.personalTime .title{color:#ffd9a0!important}
#scheduleView .event .aiDetailShow{display:none!important}
#scheduleView .event.aiNeedsDetails .aiDetailShow{display:inline-flex!important;position:absolute!important;right:8px!important;top:4px!important;height:20px!important;line-height:18px!important;padding:0 9px!important;border-radius:999px!important;font-size:11px!important;font-weight:900!important;letter-spacing:.04em!important;z-index:20!important;margin:0!important;transform:none!important;pointer-events:auto!important}
.aiDetailFloat{position:fixed!important;z-index:10000!important;min-width:240px!important;max-width:450px!important;border:1px solid #6f45a8!important;border-radius:10px!important;background:#080711!important;padding:11px 13px!important;color:#fff!important;box-shadow:0 12px 30px rgba(0,0,0,.72)!important;font-size:15.5px!important;line-height:1.35!important}
.aiDetailFloat div{font-size:15.5px!important}.aiDetailFloatTitle{font-size:15px!important;font-weight:900!important;color:#cfc3ff!important;margin-bottom:6px!important}
.aiChatButton{position:fixed!important;left:13px!important;bottom:18px!important;width:62px!important;height:62px!important;border-radius:19px!important;z-index:100!important;border:2px solid #8f5cff!important;background:#090615!important;color:#fff!important;font-size:27px!important}
.aiChatPanel{position:fixed!important;left:20px!important;bottom:96px!important;width:min(420px,calc(100vw - 36px))!important;height:560px!important;display:none;flex-direction:column!important;z-index:100!important;border:1px solid #4b3170!important;border-radius:18px!important;background:#050509!important;overflow:hidden!important}.aiChatPanel.open{display:flex!important}
.aiChatHeader{padding:14px!important;border-bottom:1px solid #2b2147!important;font-weight:650!important}.aiChatMessages{flex:1!important;overflow:auto!important;padding:12px!important;display:flex!important;flex-direction:column!important;gap:10px!important}
.aiMsg{border:1px solid #352456!important;background:#090812!important;border-radius:12px!important;padding:10px!important;line-height:1.35!important;white-space:pre-wrap!important;color:#fff!important}.aiMsg.user{border-color:#7f52ff!important}
.aiChatInput{display:flex!important;gap:8px!important;padding:12px!important;border-top:1px solid #2b2147!important}.aiChatInput input{flex:1!important}.aiChatInput button{font-weight:900!important}
.aiSuggest,#aiSuggestions{display:none!important}
`;}
function fixState(){let s=getState();if(!Array.isArray(s.custom))return;s.custom.forEach(b=>{let t=String(b.title||'').toLowerCase();let d=new Date(String(b.date||'')+'T00:00:00');if(/wind down/.test(t)&&b.start)b.end=hm(mins(b.start)+30);if(/evening routine/.test(t)&&d.getDay()===3){b.start='21:20';b.end='22:30'}if(/\bwork\b/.test(t)&&d.getDay()===3)b.end='21:20'});setState(s)}
function customPool(date){let s=getState();return(Array.isArray(s.custom)?s.custom:[]).filter(c=>Array.isArray(c.taskTexts)&&c.taskTexts.length&&(!date||c.date===date)).sort((a,b)=>mins(a.start)-mins(b.start)||mins(a.end)-mins(b.end))}
function customBlock(date,title,start,end){let s=getState();return(Array.isArray(s.custom)?s.custom:[]).find(c=>c.date===date&&clean(c.title||'')===clean(title||'')&&(!c.start||Math.abs(mins(c.start)-start)<=10)&&(!c.end||Math.abs(mins(c.end)-end)<=10))}
function closeDetails(){let f=document.getElementById('aiDetailFloat');if(f){f.remove();document.querySelectorAll('.aiDetailShow').forEach(b=>b.textContent='DETAILS')}}
function openDetails(el,btn){let old=document.getElementById('aiDetailFloat'),id=el.dataset.aiDetailId||(el.dataset.aiDetailId='d'+Math.random());if(old&&old.dataset.forEl===id){closeDetails();return}if(old)old.remove();let raw=el.dataset.aiTaskTexts||'';if(!raw)return;let box=document.createElement('div');box.id='aiDetailFloat';box.className='aiDetailFloat';box.dataset.forEl=id;box.innerHTML='<div class="aiDetailFloatTitle">Full task</div>'+raw.split('||').filter(Boolean).map(x=>'<div>• '+esc(x)+'</div>').join('');document.body.appendChild(box);let r=(btn||el).getBoundingClientRect(),br=box.getBoundingClientRect();let left=Math.min(innerWidth-br.width-8,Math.max(8,r.left));let top=r.bottom+8;if(top+br.height>innerHeight-8)top=Math.max(8,r.top-br.height-8);box.style.left=left+'px';box.style.top=top+'px'}
function markDetails(el){let title=el.querySelector('.title'),time=el.querySelector('.time');if(!title)return;let full=clean(el.dataset.aiFullTitle||el.dataset.stableBaseTitle||title.textContent||'');let protectedBlock=el.classList.contains('school')||el.classList.contains('homework')||el.classList.contains('wind')||/^(morning routine|evening routine|wind down)$/i.test(full);let need=!!el.dataset.aiTaskTexts&&!protectedBlock;let b=el.querySelector('.aiDetailShow');if(need){if(!b){b=document.createElement('button');b.className='aiDetailShow';el.appendChild(b)}b.textContent='DETAILS';b.onclick=e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation&&e.stopImmediatePropagation();openDetails(el,b)}}else if(b)b.remove();el.classList.toggle('aiNeedsDetails',need);if(time)time.style.paddingRight=need?'82px':''}
function applyCustomStyle(el,c){if(!c)return;let bg=c.bg||c.background||c.color,border=c.border||c.borderColor,text=c.textColor||c.text;if(bg)el.style.setProperty('background',bg,'important');if(border)el.style.setProperty('border-color',border,'important');if(text){el.style.setProperty('color',text,'important');el.querySelectorAll('.time,.title').forEach(x=>x.style.setProperty('color',text,'important'))}}
function normalizeDay(day){[...day.querySelectorAll('.event')].forEach(el=>{let t=clean((el.querySelector('.title')||{}).textContent||'');if(el.classList.contains('break')||el.classList.contains('aiBreakHidden')||/^available block$/i.test(t)||el.classList.contains('aiFreeHidden'))el.remove()});let days=[...document.querySelectorAll('#scheduleView .day')],date=null;try{let i=days.indexOf(day);if(i>=0)date=ymd(addDays(currentMonday,i))}catch(e){}let pool=customPool(date),rows=[];day.querySelectorAll('.event').forEach(el=>{let time=el.querySelector('.time');if(!time)return;if(!el.dataset.stableBaseTime)el.dataset.stableBaseTime=time.textContent;if(!el.dataset.stableBaseTop)el.dataset.stableBaseTop=el.style.top||'0px';let p=ptime(el.dataset.stableBaseTime);if(p)rows.push({el,t:p})});rows.sort((a,b)=>a.t.start-b.t.start||a.t.end-b.t.end);let prevEnd=0,prevBottom=-GAP;rows.forEach(r=>{let el=r.el,time=el.querySelector('.time'),titleEl=el.querySelector('.title'),title=clean(el.dataset.stableBaseTitle||(titleEl&&titleEl.textContent)||'');if(titleEl&&!el.dataset.stableBaseTitle)el.dataset.stableBaseTitle=title;let start=Math.max(r.t.start,prevEnd),end=r.t.end;if(el.classList.contains('wind')){title='Wind down';end=r.t.start+30}let wrap=day.closest('.dayWrap')||day.parentElement||day,isWed=/wed/i.test(wrap.textContent||'');if(/evening routine/i.test(title)&&isWed){start=Math.max(1280,prevEnd);end=1350}if(/\bwork\b/i.test(title)&&isWed)end=1280;let dur=Math.max(1,end-(/evening routine/i.test(title)&&isWed?start:r.t.start));if(!(/evening routine/i.test(title)&&isWed))end=start+dur;let one=end-start<=30||el.classList.contains('homework')||el.classList.contains('wind');if(time)time.textContent=one?hm(start)+'-'+hm(end)+' '+title:String(el.dataset.stableBaseTime).replace(r.t.raw,hm(start)+'-'+hm(end));let base=parseFloat(el.dataset.stableBaseTop||'0')||0,nTop=base+(start-r.t.start)*PX,nBot=base+(end-r.t.start)*PX,top=(prevEnd>0&&Math.abs(start-prevEnd)<=1)?prevBottom+GAP:Math.max(nTop,prevBottom+GAP),height=Math.max(12,nBot-top);el.style.top=top+'px';el.style.height=height+'px';prevEnd=end;prevBottom=top+height;let rec=pool.find(c=>!c.__used&&(clean(c.title||'')===title||(/grouped tasks/i.test(title)&&/grouped tasks/i.test(c.title||''))));if(!rec&&/grouped tasks/i.test(title))rec=pool.find(c=>!c.__used);if(rec){rec.__used=true;el.dataset.aiTaskTexts=rec.taskTexts.join('||');el.dataset.aiFullTitle=rec.taskTexts.join(' & ')}else delete el.dataset.aiTaskTexts;applyCustomStyle(el,customBlock(date,title,start,end));el.classList.toggle('aiOneLineSmall',one);el.classList.toggle('aiLockedGenerated',!!el.dataset.aiTaskTexts||/grouped tasks| pt\. \d+$/i.test(title));if(titleEl){titleEl.textContent=title;titleEl.style.fontWeight='650';if(one)titleEl.style.display='none'}if(time){time.style.fontWeight='760';time.style.textAlign='left'}markDetails(el)})}
function layout(){css();document.body.classList.toggle('aiScheduleActive',((document.querySelector('.tab.active')||{}).getAttribute||(()=>''))()==='scheduleView');document.querySelectorAll('#scheduleView .day').forEach(normalizeDay)}
function addBlock(a){let s=getState();s.custom=s.custom||[];s.custom.push({id:'ai-'+Date.now()+Math.random(),date:a.date,start:a.start,end:a.end,title:a.title||'Personal time',type:a.blockType||'personalTime',source:'custom',bg:a.bg||a.background||a.color,border:a.border||a.borderColor,textColor:a.textColor||a.text});setState(s)}
function applyActions(actions){let n=0;(actions||[]).forEach(a=>{if(!a||!a.type)return;if(a.type==='update_schedule'&&window.personalOSUpdateSchedule){n+=window.personalOSUpdateSchedule()||0;return}if(a.type==='create_block'&&a.date&&a.start&&a.end){addBlock(a);n++}if(a.type==='create_block_span'){let w=weekContext(),si=w.findIndex(d=>d.date===a.start_date),ei=w.findIndex(d=>d.date===a.end_date);if(si>=0&&ei>=si)for(let i=si;i<=ei;i++){addBlock({date:w[i].date,start:i===si?a.start:'06:45',end:i===ei?a.end:'22:30',title:a.title||'Personal time',blockType:a.blockType||'personalTime',bg:a.bg||a.background||a.color,border:a.border||a.borderColor,textColor:a.textColor||a.text});n++}}});try{render()}catch(e){}setTimeout(layout,0);return n}
function modelPrompt(text){return 'You are DeepSeek inside Personal OS. Answer normal questions normally. Only change the schedule when the user explicitly asks for a schedule change. For schedule changes, respond with JSON only: {"message":"short summary","actions":[...]}. Available actions: create_block {date,start,end,title,blockType,bg,border,textColor}, create_block_span {start_date,end_date,start,end,title,blockType,bg,border,textColor}, update_schedule {}. You may choose custom CSS colors. Use blockType personalTime for personal time. Personal time may visually overlap morning and evening routines; never remove or hide routines. Context: '+JSON.stringify({today:ymd(new Date()),now:hm(new Date().getHours()*60+new Date().getMinutes()),tasks:taskContext(),week:weekContext()})+'\nUser: '+text}
function parseReply(data){let msg=(data&&data.message)||'';if(Array.isArray(data&&data.actions))return{msg:msg||'Done.',actions:data.actions};let raw=String(msg||'').trim().replace(/^```(?:json)?/,'').replace(/```$/,'').trim();try{let j=JSON.parse(raw);if(Array.isArray(j.actions))return{msg:j.message||'Done.',actions:j.actions}}catch(e){}return{msg:msg||raw||'Done.',actions:null}}
function chatMsg(text,cls){let box=document.getElementById('aiChatMessages');if(!box)return null;let d=document.createElement('div');d.className='aiMsg '+(cls||'assistant');d.textContent=text;box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
async function sendChat(){let input=document.getElementById('aiChatInput'),text=(input&&input.value||'').trim();if(!text)return;input.value='';chatMsg(text,'user');let pending=chatMsg('Thinking...','assistant');try{let r=await fetch('/api/deepseek',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:modelPrompt(text),rawMessage:text,tasks:taskContext(),week:weekContext()})});let data=await r.json();if(pending)pending.remove();let parsed=parseReply(data),n=parsed.actions?applyActions(parsed.actions):0;chatMsg(parsed.msg+(n?'\nApplied '+n+' change'+(n===1?'':'s')+'.':''),'assistant')}catch(e){if(pending)pending.remove();chatMsg('DeepSeek connection failed. No schedule changes were made.','assistant')}}
function installChat(){let old=document.getElementById('aiChatPanel');if(old)old.remove();let oldBtn=document.getElementById('aiChatButton');if(oldBtn)oldBtn.remove();document.body.insertAdjacentHTML('beforeend','<button class="aiChatButton" id="aiChatButton">✦</button><div class="aiChatPanel" id="aiChatPanel"><div class="aiChatHeader">DeepSeek Assistant</div><div class="aiChatMessages" id="aiChatMessages"><div class="aiMsg">Ask DeepSeek anything, or ask it to change blocks.</div></div><div class="aiChatInput"><input id="aiChatInput" placeholder="Ask me anything..."><button id="aiChatSend">SEND</button></div></div>');let b=document.getElementById('aiChatButton'),panel=document.getElementById('aiChatPanel'),btn=document.getElementById('aiChatSend'),input=document.getElementById('aiChatInput');b.onclick=e=>{e.stopPropagation();panel.classList.toggle('open')};btn.onclick=sendChat;input.onkeydown=e=>{if(e.key==='Enter')sendChat()}}
function boot(){fixState();css();fetch(BASE,{cache:'no-store'}).then(r=>r.text()).then(code=>{(0,eval)(code);installChat();setTimeout(layout,100);new MutationObserver(()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;layout()})}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style']});setInterval(()=>{layout();if(!document.getElementById('aiChatButton'))installChat()},700)})}
document.addEventListener('click',e=>{let ev=e.target&&e.target.closest&&e.target.closest('#scheduleView .event.aiLockedGenerated');if(ev&&!e.target.closest('.aiDetailShow')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation&&e.stopImmediatePropagation()}},true);
window.addEventListener('scroll',closeDetails,true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
