// Auto-generated by lectio-export-os.js. Do not edit manually.
window.LECTIO_DATA = {
  "syncedAt": "2026-05-01T07:47:49.218Z",
  "source": "lectio.js cache",
  "dateCount": 98,
  "school": [
    {
      "date": "2026-04-20",
      "start": "08:15",
      "end": "09:10",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-04-20",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-04-20",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-04-20",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-04-20",
      "start": "12:55",
      "end": "13:50",
      "title": "Human Relationships"
    },
    {
      "date": "2026-04-20",
      "start": "14:00",
      "end": "14:55",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-04-21",
      "start": "08:15",
      "end": "09:10",
      "title": "Recap modelling"
    },
    {
      "date": "2026-04-21",
      "start": "09:20",
      "end": "10:15",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-04-21",
      "start": "10:25",
      "end": "11:20",
      "title": "Human Relationships"
    },
    {
      "date": "2026-04-21",
      "start": "11:50",
      "end": "12:45",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-04-22",
      "start": "08:15",
      "end": "09:10",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-04-22",
      "start": "09:20",
      "end": "10:15",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-04-22",
      "start": "10:25",
      "end": "11:20",
      "title": "Aktiviteten har en præsentation."
    },
    {
      "date": "2026-04-22",
      "start": "11:50",
      "end": "12:45",
      "title": "2i cas/2"
    },
    {
      "date": "2026-04-23",
      "start": "08:15",
      "end": "09:10",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-04-23",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-04-23",
      "start": "10:25",
      "end": "11:20",
      "title": "IA methodology"
    },
    {
      "date": "2026-04-23",
      "start": "10:25",
      "end": "11:00",
      "title": "IA biology meeting"
    },
    {
      "date": "2026-04-23",
      "start": "11:50",
      "end": "12:45",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-04-24",
      "start": "08:15",
      "end": "09:10",
      "title": "Recap modelling"
    },
    {
      "date": "2026-04-24",
      "start": "09:20",
      "end": "10:15",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-04-24",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-04-24",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-04-24",
      "start": "12:55",
      "end": "13:50",
      "title": "Conservation of biodiversity"
    },
    {
      "date": "2026-04-24",
      "start": "14:00",
      "end": "14:55",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-04-27",
      "start": "08:15",
      "end": "09:10",
      "title": "Fokus på IO"
    },
    {
      "date": "2026-04-27",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-04-27",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-04-27",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-04-27",
      "start": "12:55",
      "end": "13:50",
      "title": "Human Relationships"
    },
    {
      "date": "2026-04-27",
      "start": "14:00",
      "end": "14:55",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-04-28",
      "start": "08:15",
      "end": "09:10",
      "title": "Intro to probability"
    },
    {
      "date": "2026-04-28",
      "start": "09:20",
      "end": "10:15",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-04-28",
      "start": "10:25",
      "end": "11:20",
      "title": "Human Relationships"
    },
    {
      "date": "2026-04-28",
      "start": "11:50",
      "end": "12:45",
      "title": "HL only - Tech and dating"
    },
    {
      "date": "2026-04-29",
      "start": "08:15",
      "end": "09:10",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-04-29",
      "start": "09:20",
      "end": "10:15",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-04-29",
      "start": "10:25",
      "end": "11:20",
      "title": "Probability rules"
    },
    {
      "date": "2026-04-29",
      "start": "11:50",
      "end": "12:45",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-04-30",
      "start": "08:15",
      "end": "09:10",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-04-30",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-04-30",
      "start": "10:25",
      "end": "11:20",
      "title": "A4.2 Biodiversity"
    },
    {
      "date": "2026-04-30",
      "start": "11:50",
      "end": "12:45",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-01",
      "start": "08:15",
      "end": "09:10",
      "title": "Probability of events"
    },
    {
      "date": "2026-05-01",
      "start": "09:20",
      "end": "10:15",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-05-01",
      "start": "10:25",
      "end": "11:20",
      "title": "Lokaler: B2, C14"
    },
    {
      "date": "2026-05-01",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-01",
      "start": "12:55",
      "end": "13:50",
      "title": "IA pilots"
    },
    {
      "date": "2026-05-01",
      "start": "14:00",
      "end": "14:55",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-04",
      "start": "08:15",
      "end": "09:10",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-04",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-04",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-04",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-04",
      "start": "12:55",
      "end": "13:50",
      "title": "Human Relationships HL"
    },
    {
      "date": "2026-05-04",
      "start": "14:00",
      "end": "14:55",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-05-05",
      "start": "08:15",
      "end": "09:10",
      "title": "Tree diagram class"
    },
    {
      "date": "2026-05-05",
      "start": "09:20",
      "end": "10:15",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-05-05",
      "start": "10:25",
      "end": "11:20",
      "title": "Human Relationships HL"
    },
    {
      "date": "2026-05-05",
      "start": "11:50",
      "end": "12:45",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-05-06",
      "start": "08:15",
      "end": "09:10",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-05-06",
      "start": "09:20",
      "end": "10:15",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-05-06",
      "start": "11:50",
      "end": "12:45",
      "title": "2i cas/2"
    },
    {
      "date": "2026-05-06",
      "start": "13:40",
      "end": "14:00",
      "title": "EE DA"
    },
    {
      "date": "2026-05-07",
      "start": "08:15",
      "end": "09:10",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-07",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-07",
      "start": "10:25",
      "end": "11:20",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-07",
      "start": "11:50",
      "end": "12:45",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-08",
      "start": "08:15",
      "end": "09:10",
      "title": "Venn diagrams"
    },
    {
      "date": "2026-05-08",
      "start": "09:20",
      "end": "10:15",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-05-08",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-08",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-08",
      "start": "12:55",
      "end": "13:50",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-08",
      "start": "14:00",
      "end": "14:55",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-11",
      "start": "08:15",
      "end": "09:10",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-11",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-11",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-11",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-11",
      "start": "12:55",
      "end": "13:50",
      "title": "Human Relationships CP"
    },
    {
      "date": "2026-05-11",
      "start": "14:00",
      "end": "14:55",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-05-12",
      "start": "08:15",
      "end": "09:10",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-05-12",
      "start": "09:20",
      "end": "10:15",
      "title": "2i maAI/SL2"
    },
    {
      "date": "2026-05-12",
      "start": "10:25",
      "end": "11:20",
      "title": "Human Relationships CP"
    },
    {
      "date": "2026-05-12",
      "start": "11:50",
      "end": "12:45",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-05-13",
      "start": "08:15",
      "end": "09:10",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-05-13",
      "start": "09:20",
      "end": "10:15",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-05-13",
      "start": "10:25",
      "end": "11:20",
      "title": "EE Workshop"
    },
    {
      "date": "2026-05-13",
      "start": "11:50",
      "end": "14:55",
      "title": "EE Research Modules"
    },
    {
      "date": "2026-05-15",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-15",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-15",
      "start": "12:55",
      "end": "13:50",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-15",
      "start": "14:00",
      "end": "14:55",
      "title": "2i bio/SL"
    },
    {
      "date": "2026-05-18",
      "start": "08:15",
      "end": "09:10",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-18",
      "start": "09:20",
      "end": "10:15",
      "title": "2i daA/HL"
    },
    {
      "date": "2026-05-18",
      "start": "10:25",
      "end": "11:20",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-18",
      "start": "11:50",
      "end": "12:45",
      "title": "2i enB/HL"
    },
    {
      "date": "2026-05-18",
      "start": "12:55",
      "end": "13:50",
      "title": "Revision - Written work"
    },
    {
      "date": "2026-05-18",
      "start": "14:00",
      "end": "14:55",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-05-19",
      "start": "10:25",
      "end": "11:20",
      "title": "Revision - Written work"
    },
    {
      "date": "2026-05-19",
      "start": "11:50",
      "end": "12:45",
      "title": "2i psy/HL"
    },
    {
      "date": "2026-05-20",
      "start": "08:15",
      "end": "09:10",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-05-20",
      "start": "09:20",
      "end": "10:15",
      "title": "2i TOK/2"
    },
    {
      "date": "2026-05-20",
      "start": "10:25",
      "end": "11:20",
      "title": "2i cas/2"
    },
    {
      "date": "2026-05-20",
      "start": "11:50",
      "end": "14:55",
      "title": "EE Research Modules"
    },
    {
      "date": "2026-05-21",
      "start": "07:00",
      "end": "14:55",
      "title": "2i Collaborative Science Proj"
    },
    {
      "date": "2026-05-22",
      "start": "08:15",
      "end": "14:00",
      "title": "2i Collaborative Science Proj"
    },
    {
      "date": "2026-06-01",
      "start": "09:15",
      "end": "09:45",
      "title": "EE DA"
    },
    {
      "date": "2026-06-01",
      "start": "10:00",
      "end": "11:00",
      "title": "EE Workshop: referencing, etc"
    },
    {
      "date": "2026-06-03",
      "start": "08:15",
      "end": "14:55",
      "title": "EE Writing Days + Draft"
    },
    {
      "date": "2026-06-04",
      "start": "08:15",
      "end": "14:55",
      "title": "EE Writing Days + Draft"
    },
    {
      "date": "2026-06-22",
      "start": "08:15",
      "end": "14:55",
      "title": "EE Writing Days"
    },
    {
      "date": "2026-06-23",
      "start": "08:15",
      "end": "14:55",
      "title": "EE Writing Days"
    }
  ],
  "homework": [
    {
      "date": "2026-04-20",
      "subject": "2i psy/HL"
    },
    {
      "date": "2026-04-21",
      "subject": "2i maAI/SL2"
    },
    {
      "date": "2026-04-21",
      "subject": "2i psy/HL"
    },
    {
      "date": "2026-04-23",
      "subject": "2i bio/SL"
    },
    {
      "date": "2026-04-27",
      "subject": "2i psy/HL"
    },
    {
      "date": "2026-04-28",
      "subject": "2i maAI/SL2"
    },
    {
      "date": "2026-05-04",
      "subject": "2i psy/HL"
    },
    {
      "date": "2026-05-05",
      "subject": "2i maAI/SL2"
    },
    {
      "date": "2026-05-08",
      "subject": "2i maAI/SL2"
    }
  ]
};
